### ISSUE TITLE
Section Tags

### ISSUE THREAD

**Issue by patSSFC** [tlwirtz/cf-sea301-portfolio-assignment#9]
I wouldn't use so many section tags as containers.  The [second bullet under usage notes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) says not to use section as a generic container.  

I think section is used by search engines to add semantic value to parts of a page that contain things that would be considered main content.  So SE's could get confused if many things are wrapped in section tags.

**Comment by tlwirtz** [comment]
fixed with commit 3c9929e
